language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
#    - 'pypy'  # dbm test fails, remove for now...

before_install:
  - sudo apt-get install strace

install:
  - "pip install . --use-mirrors"
  - pip install -r dev_requirements.txt python-coveralls
  # See https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

branches:
  only:
    - master
    - test


script:
   - doit pyflakes
   - py.test
   - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then doit coverage; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coveralls; fi

notifications:
    email:
        on_success: change
        on_failure: change
